import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-[#f8fafc] text-slate-900 dark:bg-[#0b1021] dark:text-slate-100`}
      >
        <div className="fixed inset-0 -z-10 opacity-70 dark:opacity-60 pointer-events-none">
          <div className="absolute inset-0 gradient-bg blur-[48px]" />
        </div>

        {children}
      </body>
    </html>
  );
}
